Updating the code owners
Azure/azure-functions-core-tools pull request #3684
Opened 2024-05-15 18:59 UTC by khkh-ms

### Issue describing the changes in this PR

resolves #issue_for_this_pr

### Pull request checklist

* [ ] My changes **do not** require documentation changes
  * [ ] Otherwise: Documentation issue linked to PR
* [ ] My changes **do not** need to be backported to a previous version
  * [ ] Otherwise: Backport tracked by issue/PR #issue_or_pr
* [ ] I have added all required tests (Unit tests, E2E tests)

2024-05-15 19:02 UTC, arroyc approved these changes

2024-05-17 17:38 UTC, fabiocav requested changes

2024-05-17 17:38 UTC, fabiocav commented on CODEOWNERS
> +*.yml @khkh-ms @VpOfEngineering @arroyc
Use a group instead of individual accounts.

Would be good to consider doing the same to replace what is in line 17

2024-07-10 20:47 UTC, fabiocav commented
Closing stale PR.

2024-07-10 20:47 UTC, closed without merging