Converted the authorization level value passed by the user to upper-c…
Azure/azure-functions-core-tools pull request #4157
Opened 2024-11-11 17:50 UTC by yonahcitron

### Issue describing the changes in this PR

Fixes [#3779](https://github.com/Azure/azure-functions-core-tools/issues/3779)

The technical cause of the issue was that value of the '--authlevel' param from the user is first being converted to an AuthorizationLevel enum from the Microsoft.Azure.WebJobs.Extensions.Http package, representing the C# programming model strings.

In the C# programming model, authorization level strings only capitalise the first letter.
In the Python programming model, authorization level strings are entirely upper-case.

Since we are using C# enums, we need to manually convert them to upper-case when making them strings for Python templates.

### Pull request checklist

* [x] My changes **do not** require documentation changes
  * [ ] Otherwise: Documentation issue linked to PR
* [x] My changes **do not** need to be backported to a previous version
  * [ ] Otherwise: Backport tracked by issue/PR #issue_or_pr
* [ ] I have added all required tests (Unit tests, E2E tests)

2025-03-12 22:45 UTC, liliankasem submitted a review, later dismissed
Validated this fix, thanks!

2025-03-12 22:46 UTC, liliankasem commented
/azp run

2025-03-13 20:02 UTC, aishwaryabh approved these changes

2025-03-13 20:12 UTC, jviau requested changes

2025-03-13 20:12 UTC, jviau commented on src/Azure.Functions.Cli/Actions/LocalActions/CreateFunctionAction.cs
> +                var providedInputs = new Dictionary<string, string>() { { GetFunctionNameParamId, FunctionName }, { HttpTriggerAuthLevelParamId, AuthorizationLevel?.ToString().ToUpper() } };
```suggestion
                var providedInputs = new Dictionary<string, string>() { { GetFunctionNameParamId, FunctionName }, { HttpTriggerAuthLevelParamId, AuthorizationLevel?.ToString().ToUpperInvariant() } };
```

2025-04-18 16:36 UTC, liliankasem commented
resolved by #4382

2025-04-18 16:36 UTC, closed without merging